steps:
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: sed yaml secrets
  entrypoint: bash
  args:
  - '-c'
  - 'sed -i "s#@KONG_PG_PASSWORD@#$$KONG_PG_PASSWORD#g" config/kong-deployment.yaml \
    && sed -i "s#@KONG_PG_PASSWORD@#$$KONG_PG_PASSWORD#g" config/kong-job.yaml \
	  && sed -i "s#@KONG_PG_PASSWORD@#$$KONG_PG_PASSWORD#g" config/kong-statefulSet.yaml'
  args:
  secretEnv:
  - 'KONG_PG_PASSWORD'
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Prepare deploy'
  args:
  - 'prepare'
  - '--filename=$_K8S_YAML_PATH'
  - '--image=$_IMAGE_NAME:$_IMAGE_VERSION'
  - '--app=$_K8S_APP_NAME'
  - '--version=$_IMAGE_VERSION'
  - '--namespace=$_K8S_NAMESPACE'
  - '--output=output'
  - '--annotation=gcb-build-id=$BUILD_ID'
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   id: 'Apply deploy'
#   args:
#   - 'apply'
#   - '--filename=$_OUTPUT_BUCKET_PATH/expanded/*'
#   - '--namespace=$_K8S_NAMESPACE'
#   - '--cluster=$_GKE_CLUSTER'
#   - '--location=$_GKE_LOCATION'
#   secretEnv:
#   - 'KONG_PG_PASSWORD'
images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'
substitutions:
  _DOCKERFILE_PATH: Dockerfile
  _IMAGE_NAME:
  _IMAGE_VERSION:
  _GKE_CLUSTER:
  _GKE_LOCATION:
  _K8S_YAML_PATH:
  _K8S_APP_NAME:
  _K8S_NAMESPACE:
  _OUTPUT_BUCKET_PATH:
options:
  substitution_option: 'ALLOW_LOOSE'
tags: [$_K8S_APP_NAME']

availableSecrets:
  secretManager:
  - versionName: projects/promoes/secrets/kong-pg-password/versions/latest
    env: 'KONG_PG_PASSWORD'