steps:
- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Prepare deploy'
  entrypoint: bash
  args:
  - '-c'
  - 'sed -i "s#@KONG_PG_PASSWORD@#$$KONG_PG_PASSWORD#g" ./config/kong-deployment.yaml \
    && sed -i "s#@KONG_PG_PASSWORD@#$$KONG_PG_PASSWORD#g" ./config/kong-job.yaml \
	  && sed -i "s#@KONG_PG_PASSWORD@#$$KONG_PG_PASSWORD#g" ./config/kong-statefulSet.yaml \
    && gke-deploy prepare \
    --filename=$_K8S_YAML_PATH \
    --image=$_IMAGE_NAME:$_IMAGE_VERSION \
    --app=$_K8S_APP_NAME \
    --version=$_IMAGE_VERSION \
    --namespace=$_K8S_NAMESPACE \
    --output=output \
    --annotation=gcb-build-id=$BUILD_ID'
  secretEnv:
  - 'KONG_PG_PASSWORD'
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   id: 'Apply deploy'
#   args:
#   - 'apply'
#   - '--filename=$_OUTPUT_BUCKET_PATH/expanded/*'
#   - '--namespace=$_K8S_NAMESPACE'
#   - '--cluster=$_GKE_CLUSTER'
#   - '--location=$_GKE_LOCATION'
#   secretEnv:
#   - 'KONG_PG_PASSWORD'
images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'
substitutions:
  _DOCKERFILE_PATH: Dockerfile
  _IMAGE_NAME: 'gcr.io/promoes/kong-api-gateway-1'
  _IMAGE_VERSION: '1.0.0'
  _GKE_CLUSTER: 'gke-cluster-1'
  _GKE_LOCATION: 'us-central1-c'
  _K8S_YAML_PATH: 'config'
  _K8S_APP_NAME: 'kong-gateway'
  _K8S_NAMESPACE: 'kong'
  _OUTPUT_BUCKET_PATH: 'gs://cloudbuild-config-bucket/kong-config'
options:
  substitution_option: 'ALLOW_LOOSE'
tags: [$_K8S_APP_NAME]

availableSecrets:
  secretManager:
  - versionName: projects/promoes/secrets/kong-pg-password/versions/latest
    env: 'KONG_PG_PASSWORD'